/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpu_GPUmm */

#ifndef _Included_gpu_GPUmm
#define _Included_gpu_GPUmm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gpu_GPUmm
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_init
  (JNIEnv *, jclass);

/*
 * Class:     gpu_GPUmm
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_destroy
  (JNIEnv *, jclass);

/*
 * Class:     gpu_GPUmm
 * Method:    selfmm
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_selfmm
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     gpu_GPUmm
 * Method:    power
 * Signature: ([FIZ)V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_power
  (JNIEnv *, jclass, jfloatArray, jint, jboolean);

/*
 * Class:     gpu_GPUmm
 * Method:    connect
 * Signature: ([F[I[II)V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_connect
  (JNIEnv *, jclass, jfloatArray, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
